# Introdução à Linguagem Python - Parte 4

Agora, veremos a parte emocionante da história. Iremos ver como resolver problemas físicos com Python!

##Recursos numéricos disponíveis
###Numpy

É uma biblioteca que oferece diversas funções e utilidades numéricas e matemáticas, inclusive estatísticas e de álgebra linear. Para uma referência mais completa, não existe lei no Brasil que impeça vc de acessar http://docs.scipy.org/doc/numpy/reference/index.html. Recomendo!

De início, começarei mostrando o recurso mais simples, porém o mais poderoso (na minha humilde opinião), do Numpy: Arrays! Mas como diriam os jovens de hoje: "Gente, qual a necessidade disso?". Pois bem, deixe-me mostrar!

In [1]:
# Listas numéricas normal em Python
list1 = [2.3,4.0,1.2]
list2 = [1.0,1.0,2.0]

# Operação aritmética de soma das listas
list3 = list1 + list2
print "list1 + list2 =", list3

# Produto entre as listas
list3 = list1*list2
print "list1*list2 =", list3

# Soma de um valor constante a uma lista
list3 = 2.0 + list1
print "list1 + 2 =", list3

list1 + list2 = [2.3, 4.0, 1.2, 1.0, 1.0, 2.0]


TypeError: can't multiply sequence by non-int of type 'list'

Deu ruim, né? Só "funciona" a operação de soma, que nada mais é que uma concatenação de listas normais em Python. Pois bem, precisamos de uma ferramenta que nos permita trabalhar no $\mathbb{R}^n$, senão o sofrimento será grande para realizar operações.

Então, eis que surge nosso HERÓI: Os Arrays do Numpy! Vejamos...

In [2]:
# Importando o numpy
import numpy as np # Para facilitar, vamos chamar de np para quando formos utilizar as funções

# Criando um array vazio
v1 = np.array([])
print "Array 1"
print "v1 =", v1

# Criando um array com componentes conhecidas
v2 = np.array([1.0,2.0,3.0])
print "Array 2"
print "v2 =", v2

# Alternativamente...
v2 = np.array([1.0,
               2.0,
               3.0])
print "Array 3"
print "v2 =", v2

Array 1
v1 = []
Array 2
v2 = [ 1.  2.  3.]
Array 3
v2 = [ 1.  2.  3.]


Parece com lista, não é? Mas não é! Vamos tentar operar como fizemos com as listas!

In [3]:
# Dois arrays
v1 = np.array([1.0,
               2.5,
               2.0
               ])
v2 = np.array([2.0,
               0.5,
               -2.0
               ])

# Operação de soma entre vetores
v3 = v1 + v2
print "v1 + v2 =", v3

# Produto (?) entre vetores
v3 = v1*v2
print "v1*v2 =", v3

# Soma de uma constante a um array
v3 = v1 + 1.0
print "v1 + 1 =", v3

v1 + v2 = [ 3.  3.  0.]
v1*v2 = [ 2.    1.25 -4.  ]
v1 + 1 = [ 2.   3.5  3. ]


Óptimo, não é? Têm o comportamento matemático esperado para vetores. Bom, além disso, podemos adicionar componentes a um array já existente, o que vai ser muito demasiadamente útil em cálculos no qual se faz necessário armazenar resultados! Vejamos como é bem simples...

In [4]:
# Criando um array vazio
v1 = np.array([])
print "v1 =", v1

# Adicionando um componente
v1 = np.append(v1, 1.0)
print "v1 =", v1

v1 = []
v1 = [ 1.]


Assim como também podemos tirar elementos facilmente...

In [5]:
# Criando um array
v1 = np.array([1.0, 2.0, 3.0, 4.0])
print "v1 =", v1

# Retirando o componente 3.0
v1 = np.delete(v1, 2)
print "v1 =", v1

# Retirando agora o 2.0 e 4.0
v1 = np.delete(v1, [1, 2])
print "v1 =", v1

# Retirando o último componente sem saber quanto há no array
v1 = np.array([1.0, 2.0, 3.0, 4.0])
v1 = np.delete(v1, -1)
print "v1 =", v1

v1 = [ 1.  2.  3.  4.]
v1 = [ 1.  2.  4.]
v1 = [ 1.]
v1 = [ 1.  2.  3.]


Se temos vetores, temos também Matrizes! Mas como? Calma... vamos ver.

In [6]:
# Declarando uma matriz
mat1 = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]])
print 'mat1 =\n', mat1

# Alternativamente...
mat1 = np.array([[1.0,2.0,3.0],
                 [4.0,5.0,6.0],
                 [7.0,8.0,9.0]])
print 'mat1 =\n', mat1

mat1 =
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
mat1 =
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


Como é de se esperar, uma matriz é um Array com Arrays internos. E como podemos acessar? De forma semelhante ao que se faz com Listas. Miremos...

In [7]:
# Declarando um vetor
v1 = np.array([1.0,2.0,3.0,4.0])
print 'v1[1] =', v1[1]

# Declarando uma matriz
mat1 = np.array([[1.0,2.0,3.0],
                 [4.0,5.0,6.0],
                 [7.0,8.0,9.0]])
print 'mat1[1,2] =', mat1[1,2]

# Alternativamente para matrizes...
print 'mat1[1,2] =', mat1[1][2]

# Extra... Matriz transposta
mat2 = mat1.T
print '\nTransposta de mat1'
print 'mat2 =\n', mat2

v1[1] = 2.0
mat1[1,2] = 6.0
mat1[1,2] = 6.0

Transposta de mat1
mat2 =
[[ 1.  4.  7.]
 [ 2.  5.  8.]
 [ 3.  6.  9.]]


Bom... já sabemos somar (logo, sabemos subtrair também) arrays em arrays e somar uma constante, agora vamos fechar outras aritméticas básicas!

In [8]:
# Declarando umas matrizes
mat1 = np.array([[1.0,2.0,3.0],
                 [4.0,5.0,6.0],
                 [7.0,8.0,9.0]])
mat2 = mat1.T

# Declarando uns vetores
v1 = np.array([1.,2.,5.])
v2 = np.array([3.,-1.,1.])

# Multiplicando objetos arrays por uma constante
print 'Multiplicação por uma constante\n'
mat3 = mat1*2.0
v3 = v1*2.0
print 'mat3 =\n', mat3, '\nv3 =', v3

# Produto interno entre vetores (transposta é automática)
print '\nProduto interno de vetores'
v1_dot_v2 = np.dot(v1,v2)
print 'v1.v2 =', v1_dot_v2

# Produto externo (tensorial) entre vetores (transposta é automática)
print '\nProduto externo (tensorial) de vetores'
v1_x_v2 = np.outer(v1,v2)
print 'v1 x v2 =\n', v1_x_v2

# Produto matricial entre duas matrizes
print '\nProduto matrical'
mat1_dot_mat2 = np.dot(mat1,mat2)
print 'mat1.mat2 =\n', mat1_dot_mat2

Multiplicação por uma constante

mat3 =
[[  2.   4.   6.]
 [  8.  10.  12.]
 [ 14.  16.  18.]] 
v3 = [  2.   4.  10.]

Produto interno de vetores
v1.v2 = 6.0

Produto externo (tensorial) de vetores
v1 x v2 =
[[  3.  -1.   1.]
 [  6.  -2.   2.]
 [ 15.  -5.   5.]]

Produto matrical
mat1.mat2 =
[[  14.   32.   50.]
 [  32.   77.  122.]
 [  50.  122.  194.]]


Agora que sabemos o basicão de matrizes e vetores, podemos tentar ver como é difícil resolver sistemas lineares com o Numpy! Vamos lá...

Considere o sistema linear na forma matricial:

$$
\begin{equation}
\begin{bmatrix}
1 & 2 & 1 \\
1 & 0 & 1 \\
2 & 5 & -3
\end{bmatrix}
\cdot 
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
= 
\begin{bmatrix}
1 \\
1 \\
2
\end{bmatrix}
\end{equation}
$$

Abaixo, segue uma complicadíssima resolução em Python!

In [9]:
# Declarando a matriz dos coeficientes
A = np.array([[1.,2.,1.],
              [1.,0.,1.],
              [2.,5.,-3.]])

# Declarando o vetor dos termos independentes
b = np.array([1.,1.,2.])

# Resolvendo a equação
x = np.linalg.solve(A,b)
print "x =", x

x = [ 1.  0.  0.]


## Scipy

Com a biblioteca Scipy, temos mais uma infinidade de recursos e rotinas prontas, que podem agilizar bastante a vida da pessoa. Por exemplo, a rotina $\texttt{fsolve()}$, que nos auxilia a calcular soluções de equações não-lineares.

### fsolve
#### Exemplo 1

Encontre as raízes da equação abaixo:

$$
f(x) = x^3 + 1/x -5x^2 + 10
$$

Numericamente, quem não chuta bem, não faz o gol. Então, precisamos ter uma ideia de qual seria um bom valor de chute inicial. Além disso, precisamos confirmar a unicidade da solução no domínio que será estudado. Para tanto, vamos avaliar graficamente a função.

In [10]:
import numpy as np
import matplotlib.pyplot as plt

# Definindo a função
def f(x):
    return x**2.0 + 1./x - 5.*x**2.0 + 10.0

# Definindo a discretização do contínuo para evaluação da função
x = np.linspace(0.001,2.,200)

# Calculando os valores discretos da função
y = f(x)

# Plotando

plt.figure()
plt.plot(x,y,label='f(x)')
plt.grid(True)
plt.show()

Vemos, então, que a solução está contida no intervalo $[0,2]\in\mathbb{R}$. Vamos escolher $x_0 = 2$ como chute inicial.

In [11]:
from scipy.optimize import fsolve
ysol = fsolve(f,2.0) # Entra a Eq e o chute inicial
print ysol

[ 1.62894851]


E se quisermos resolver um sistema não-linear? Nesse caso, muda-se apenas a declaração das equações do sistema e a quantidade de chutes iniciais, sendo 1 para cada variável.

Vamos resolver o seguinte sistema não-linear:

$$
\begin{equation}
\left\{
\begin{array}{l}
x + \frac{1}{2}(x - y)^3 = 1 \\
\frac{1}{2}(y-x)^3 + y = 0
\end{array}\right.
\end{equation}
$$

In [12]:
def equations(p):
    x , y = p
    return (x + 0.5*(x-y)**3.0 - 1.0, 0.5*(y-x)**3.0 + y)

x, y = fsolve(equations, (0,0))
print 'x = ', x
print 'y = ', y

x =  0.841163901914
y =  0.158836098086


Temos, portanto, a solução para o chute inicial fornecido.